name: base
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - streamlit>=1.28.0
  - pandas>=1.5.0
  - plotly>=5.0.0
  - requests>=2.28.0
  - matplotlib>=3.7.0
  - scikit-learn>=1.3.0
  - biopython>=1.80
  - python-dotenv>=0.19.0
  - pyyaml>=6.0
  - psycopg2>=2.9.0
  - flake8
  - pytest
  - pip
  - pip:
    - fpdf2>=2.7.0
    - python-docx>=0.8.0