# Terraform code generated by CloudProvisioner for organism 'organism_1753514204053_uzcntu'
# Generated at: 2025-07-26T07:16:44.053Z

provider "google" {
  project = "your-project-id"
  region  = "us-central1"
}


# GKE Cluster for organism organism_1753514204053_uzcntu
resource "google_container_cluster" "organism_1753514204053_uzcntu_cluster" {
  name               = "organism_1753514204053_uzcntu-gke-cluster"
  location           = "us-central1"
  enable_autopilot   = true
  
  release_channel {
    channel = "STABLE"
  }
}


# Outputs for organism organism_1753514204053_uzcntu
output "organism_organism_1753514204053_uzcntu_status" {
  value       = "Infrastructure provisioned successfully"
  description = "Status of infrastructure for organism organism_1753514204053_uzcntu"
}
