# Terraform code generated by CloudProvisioner for organism 'organism_1753513943874_yybqnk'
# Generated at: 2025-07-26T07:13:08.909Z

provider "google" {
  project = "your-project-id"
  region  = "us-central1"
}


# Outputs for organism organism_1753513943874_yybqnk
output "organism_organism_1753513943874_yybqnk_status" {
  value       = "Infrastructure provisioned successfully"
  description = "Status of infrastructure for organism organism_1753513943874_yybqnk"
}
