# Terraform code generated by CloudProvisioner for organism 'organism_1753514219058_kwn6zl'
# Generated at: 2025-07-26T07:16:59.059Z

provider "google" {
  project = "your-project-id"
  region  = "us-central1"
}


# GKE Cluster for organism organism_1753514219058_kwn6zl
resource "google_container_cluster" "organism_1753514219058_kwn6zl_cluster" {
  name               = "organism_1753514219058_kwn6zl-gke-cluster"
  location           = "us-central1"
  enable_autopilot   = true
  
  release_channel {
    channel = "STABLE"
  }
}


# Outputs for organism organism_1753514219058_kwn6zl
output "organism_organism_1753514219058_kwn6zl_status" {
  value       = "Infrastructure provisioned successfully"
  description = "Status of infrastructure for organism organism_1753514219058_kwn6zl"
}
