# Development Environment Configuration
# DNA-Lang Platform - GCP Development Environment

project_id: "dna-lang-dev"
organization_id: "your-org-id"
environment: "development"

# Security Configuration
security_level: "RELAXED"
encryption:
  at_rest: "GOOGLE_DEFAULT_ENCRYPTION"
  in_transit: "TLS_1_2"
  
# Access Control
authentication:
  mfa_required: false
  session_timeout: 14400  # 4 hours
  ip_whitelist_enabled: false
  
# Network Security
vpc:
  private_google_access: false
  flow_logs: false
  firewall_rules: "PERMISSIVE"

# Monitoring and Logging
monitoring:
  audit_logs: "ADMIN_READ"
  data_access_logs: false
  admin_activity_logs: true
  system_event_logs: false
  
# Backup and Recovery
backup:
  frequency: "NONE"
  retention_days: 7
  cross_region_backup: false
  
# Compliance
compliance:
  hipaa_compliant: false
  gdpr_compliant: false
  data_residency: "US"
  
# Resource Constraints
resource_limits:
  max_compute_instances: 50
  max_storage_tb: 20
  max_network_bandwidth_gbps: 2
  
# Development Features
dev_features:
  auto_shutdown: true
  cost_alerts: true
  synthetic_data_only: true