# Production Environment Configuration
# DNA-Lang Platform - GCP Production Environment

project_id: "dna-lang-prod"
organization_id: "your-org-id"
environment: "production"

# Security Configuration
security_level: "STRICT"
encryption:
  at_rest: "CUSTOMER_MANAGED_ENCRYPTION_KEY"
  in_transit: "TLS_1_3"
  
# Access Control
authentication:
  mfa_required: true
  session_timeout: 3600  # 1 hour
  ip_whitelist_enabled: true
  
# Network Security
vpc:
  private_google_access: true
  flow_logs: true
  firewall_rules: "RESTRICTIVE"

# Monitoring and Logging
monitoring:
  audit_logs: "ALL_SERVICES"
  data_access_logs: true
  admin_activity_logs: true
  system_event_logs: true
  
# Backup and Recovery
backup:
  frequency: "DAILY"
  retention_days: 90
  cross_region_backup: true
  
# Compliance
compliance:
  hipaa_compliant: true
  gdpr_compliant: true
  data_residency: "US"
  
# Resource Constraints
resource_limits:
  max_compute_instances: 10
  max_storage_tb: 100
  max_network_bandwidth_gbps: 10