# Staging Environment Configuration
# DNA-Lang Platform - GCP Staging Environment

project_id: "dna-lang-staging"
organization_id: "your-org-id"
environment: "staging"

# Security Configuration
security_level: "MODERATE"
encryption:
  at_rest: "GOOGLE_DEFAULT_ENCRYPTION"
  in_transit: "TLS_1_2"
  
# Access Control
authentication:
  mfa_required: false
  session_timeout: 7200  # 2 hours
  ip_whitelist_enabled: false
  
# Network Security
vpc:
  private_google_access: true
  flow_logs: false
  firewall_rules: "MODERATE"

# Monitoring and Logging
monitoring:
  audit_logs: "ADMIN_READ,DATA_READ,DATA_WRITE"
  data_access_logs: false
  admin_activity_logs: true
  system_event_logs: true
  
# Backup and Recovery
backup:
  frequency: "WEEKLY"
  retention_days: 30
  cross_region_backup: false
  
# Compliance
compliance:
  hipaa_compliant: true
  gdpr_compliant: true
  data_residency: "US"
  
# Resource Constraints
resource_limits:
  max_compute_instances: 20
  max_storage_tb: 50
  max_network_bandwidth_gbps: 5